### ISSUE TITLE
I  can`t   understand  

### ISSUE THREAD

**Issue by zey28** [andresmijares/async-redux-saga#2]
Hi,can  you   tell me     when  `loadDashboard`  is  been  called   ?

**Comment by nigelterry** [comment]
In CustomMixin.js,  this.props.loadDashboard() is called. LoadDashboard is defined as a function that dispatches the LOAD_DASHBOARD action in panel.js where it is mapped to props so as to be accessible as this.props.loadDashboard. CustomMixin is imported as Mixin in Panel.js and adds the componentDidMount method to each panel.

So once the panel has mounted, the LOAD_DASHBOARD action is dispatched which starts the loading of all 3 panels in rootSaga in sagas/index.js
